# Generated by Django 4.2.13 on 2024-07-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import helpers.paths


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address_text", models.TextField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(default="India", max_length=255)),
                ("zipcode", models.PositiveBigIntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Company name", max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.paths.get_company_image_path,
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("nb_contact", models.PositiveIntegerField(blank=True, null=True)),
                ("sales_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address_text", models.TextField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(default="India", max_length=255)),
                ("zipcode", models.PositiveBigIntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(default="Contact name", max_length=255),
                ),
                (
                    "last_name",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.paths.get_company_image_path,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.paths.get_contact_image_path,
                    ),
                ),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("has_newsletter", models.BooleanField(default=False)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("nb_notes", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("sales_id", models.PositiveIntegerField(blank=True, null=True)),
                ("background", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("stage", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                ("nb_notes", models.PositiveIntegerField(blank=True, null=True)),
                ("sales_id", models.PositiveIntegerField(blank=True, null=True)),
                ("index", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal",
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deals",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Tag name", max_length=255)),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="DealContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_contact_mappings",
                        to="crm.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_contact_mappings",
                        to="crm.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Contact",
                "verbose_name_plural": "Deal Contact Mappings",
                "unique_together": {("deal", "contact")},
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="contacts",
            field=models.ManyToManyField(
                related_name="contacts", through="crm.DealContact", to="crm.contact"
            ),
        ),
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("sales_id", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_note",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Notes",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="crm.tag"
            ),
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=helpers.paths.get_recording_file_path,
                    ),
                ),
                ("transript", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_record",
                        to="crm.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_record",
                        to="crm.deal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Call Recordings",
            },
        ),
    ]
