# Generated by Django 4.2.13 on 2024-07-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="recommended_language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="budget",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="category",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Copywriting"),
                    (2, "Print project"),
                    (3, "UI Desging"),
                    (4, "Website Design"),
                    (5, "Other"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Opportunity"),
                    (2, "Proposal"),
                    (3, "In Negotiation"),
                    (4, "Won"),
                    (5, "Lost"),
                    (7, "Delayed"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("due_date", models.DateTimeField()),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task",
                        to="crm.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task",
                        to="crm.deal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deal Tasks",
            },
        ),
        migrations.CreateModel(
            name="ContactPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("follow_up", models.CharField(blank=True, max_length=255, null=True)),
                ("persona", models.TextField()),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persona",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Personas",
            },
        ),
        migrations.CreateModel(
            name="CallSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_summary",
                        to="crm.callrecord",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_summary",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Call Summary",
            },
        ),
    ]
