# Generated by Django 4.2.13 on 2024-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_contact_recommended_language_deal_budget_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="last_name",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="deal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
