# Generated by Django 4.2.13 on 2024-07-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_rename_last_name_contact_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="name",
            new_name="item",
        ),
        migrations.RemoveField(
            model_name="contactnote",
            name="sales_id",
        ),
        migrations.AddField(
            model_name="contactnote",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_note",
                to="crm.deal",
            ),
        ),
        migrations.AlterField(
            model_name="contactnote",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
