# Generated by Django 4.2.13 on 2024-07-05 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_rename_name_tasks_item_remove_contactnote_sales_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callsummary",
            name="call",
        ),
        migrations.RemoveField(
            model_name="callsummary",
            name="contact",
        ),
        migrations.DeleteModel(
            name="CallRecord",
        ),
        migrations.DeleteModel(
            name="CallSummary",
        ),
    ]
