# Generated by Django 4.2.13 on 2024-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_remove_callsummary_call_remove_callsummary_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "opportunity"),
                    (2, "proposal-sent"),
                    (3, "in-negotiation"),
                    (4, "won"),
                    (5, "lost"),
                    (7, "delayed"),
                ],
                default=1,
            ),
        ),
    ]
