# Generated by Django 4.2.13 on 2024-07-05 21:37

from django.db import migrations, models
import django.db.models.deletion
import helpers.paths


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0005_remove_callsummary_call_remove_callsummary_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=helpers.paths.get_recording_file_path,
                    ),
                ),
                ("transript", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_record",
                        to="crm.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_record",
                        to="crm.deal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Call Recordings",
            },
        ),
        migrations.CreateModel(
            name="CallSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_summary",
                        to="voicecall.callrecord",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_summary",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Call Summary",
            },
        ),
    ]
