# Generated by Django 4.2.13 on 2024-07-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "voicecall",
            "0002_remove_callrecord_transript_callrecord_transcript_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callsummary",
            name="call",
        ),
        migrations.RemoveField(
            model_name="callsummary",
            name="contact",
        ),
        migrations.AddField(
            model_name="callrecord",
            name="call_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_summary",
                to="voicecall.callsummary",
            ),
        ),
        migrations.AddField(
            model_name="callsummary",
            name="to_do",
            field=models.TextField(blank=True, null=True),
        ),
    ]
